### ISSUE TITLE
Define lazy constraints (gurobi specific)

### ISSUE THREAD

**Issue by kjartan-at-bravos** [Bravos-Power/pyoframe#23]
The [lp-format used by Gurobi](https://www.gurobi.com/documentation/current/refman/lp_format.html) has a section for defining [lazy constraints](https://www.gurobi.com/documentation/current/refman/lazy.html).

It would be nice to be able to set this attribute for constraints defined in pyoframe prior to writing the lp file. 

Since constraints are defined by the natural syntax `model.my_constraint = x <= 2`, I assume the attribute would be set in a second step `model.my_constraint.Lazy = 2`

**Comment by staadecker** [comment]
After our discussion, I think we decided that handling custom Gurobi features in the .lp file will not be done

**Comment by kjartan-at-bravos** [comment]
Agree!
