### ISSUE TITLE
Set attributes on solver variables 

### ISSUE THREAD

**Issue by kjartan-at-bravos** [Bravos-Power/pyoframe#39]
In gurobi one can use MIP start and variable hints to speed up the solution. This requires that the attributes `Start`, respectively `VarHintVal` are set on the variables of the model. Typically, these are set from variable values of a previous solution of a related problem.  

It would be great to be able to set this from pyoframe prior to calling `.solve`.

**Comment by staadecker** [comment]
Done in #41
